#!/usr/bin/env python
# coding: utf-8

# In[1]:


#Import all important packages
import numpy as np
import glob


# In[2]:


# Function
#--------------------------------------#
def get_signal_optimal(file_path):
    '''
    Reads signals from a file at FILE_PATH generated by a 1D CCD.
    This one replaces append()s w/ assignments to save time & space.
    '''
    # These constants better b defined at start of the whole code
    CCD_PIXELS = 2048
    LENGTH_HEADER = 17
    LENGTH_FOOTER = 1
    
    pixel = np.arange(0, CCD_PIXELS)
    
    files = glob.glob(file_path)
    n_files = len(files)
    signal = np.zeros((n_files, CCD_PIXELS)) # An empty 2D array of zeros
    
    for i in range(n_files):
        pixNum, s = np.genfromtxt(files[i], dtype=(float), skip_header=LENGTH_HEADER, skip_footer=LENGTH_FOOTER, unpack=True)
        signal[i] = s
    return(pixel, signal)
#--------------------------------------#


# Navigate to raw data
#--------------------------------------#
lab2_file_path = 'example_data/lab2_neon_data/*.txt'
#--------------------------------------#


# Import data by executing function
#--------------------------------------#
pixel, signal = get_signal_optimal(lab2_file_path)
#--------------------------------------#

